### ISSUE TITLE
Project Notes (10/29/2019)

### ISSUE THREAD

**Issue by maileen13** [eeb313-2019/beeplyr#4]
Group Name: Beeplyr

Roles within the group will be rotate each week. This will be decided at the beginning of the meeting. 

#Code of Conduct
-Primary communication channel will be the Facebook group chat
-Conflict will be resolved by time limited structured conversation (20 minutes)
Meetings will be decided in advance and in conjunction with teammate availability. 

#Team Strengths
Sophia: has some experience with pollination data, passionate about obscure bee genera.
Natasha: feels comfortable researching R strategies, provides snacks and wholesome atmosphere that is conducive to productivity. 
Madison: developing creative presentation formats and visualisation of data, 

#Possible data ideas
Plant and bee pollination correlations/ dispersal of plant type (emergence and flowering time)

**Comment by ghost** [comment]
@maileen13 This is great! Thanks
